### ISSUE TITLE
Panic "byte index 3236 is not a char boundary" on latest available release and first run.

### ISSUE THREAD

**Issue by AqilCont** [RDambrosio016/RSLint#60] opened 2020-10-23 22:33 UTC
### Code
> Not relevant, needed code is below.

### Meta
`rslint -V`: 0.2.1

### Error Output

```cmd
current_dir> rslint_cli-windows d:/projects/nodejs/someproject
The linter panicked unexpectedly. This is a bug.

We would appreciate a bug report: https://github.com/RDambrosio016/RSLint/issues/new?labels=ILE%2C+bug&template=internal-linter-error.md

Please include the following info:

message: byte index 3236 is not a char boundary; it is inside '™' (bytes 3234..3237) of `
// Filesystem modules
import { existsSync } from "fs"; import { project, messages } from "../config.js";

// Creates random strings for re-importing
import { list, trim } from "./f.js";

// This is the command(singular) handler, which imports comma`[...]
location: crates\rslint_parser\src\lossless_tree_sink.rs:74:28

```

**Comment by RDambrosio016** [comment] 2020-10-23 22:35
This is a known issue, its quite obscure so i dont know the root cause of it yet but i am looking into it 🙂

**Comment by AqilCont** [comment] 2020-10-23 22:36
Ohh ok thanks! Looking forward to using it after it is fixed. Loved this project because eslint is a bloated pain to me sometimes xd

**Comment by Stupremee** [comment] 2020-10-26 21:24
@AqilCont This will be fixed in my next PR. Will take an hour probably :+1:

**Comment by AqilCont** [comment] 2020-10-27 01:23
Ohhhh I'm really glad you're working on it! From what I've seen, I'm really excited to start using this tool starting from when this issue is fixed :DDD. Thanks a lot for the updates!
I actually really want to help myself, but these are the times I regret not learning much Rust[I miss out on contributing to so many cool projects like this :'(].

**Comment by RDambrosio016** [comment] 2020-10-27 01:25
There is always time to learn more rust! https://doc.rust-lang.org/book/

**Comment by Stupremee** [comment] 2020-10-28 19:11
Now it's fixed :tada:

**Closed by Stupremee** 2020-10-28 19:11 UTC
Labels: C-bug, ILE, T-Parser
